name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Java (for Allure)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Allure
        uses: actions/setup-allure@v1
        with:
          allure-version: 2.35.1

      - name: Run pytest with allure
        run: |
          pytest -v --alluredir=reports/allure-results || true
          ls -R reports || true

      - name: Generate allure report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean || true
          ls -R reports || true

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results
          if-no-files-found: ignore

      - name: Upload allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
          if-no-files-found: ignore
