name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with allure
        run: |
          mkdir -p reports/allure-results
          pytest -vv --maxfail=1 --disable-warnings --alluredir=reports/allure-results

      - name: Debug report folder
        if: always()
        run: ls -R reports || echo "No reports directory found"

      - name: Install Allure CLI
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz
          tar -zxvf allure-2.35.1.tgz
          sudo mv allure-2.35.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Generate allure report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-report || echo "No allure results to generate"

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results
          if-no-files-found: warn

      - name: Upload allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
          if-no-files-found: warn
