name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Allure results folder
      run: mkdir -p reports/allure-results

    - name: Run tests
      run: |
        pytest -v --alluredir=reports/allure-results || true

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
        unzip allure-2.35.1.zip -d /opt/
        echo "/opt/allure-2.35.1/bin" >> $GITHUB_PATH

    - name: Generate Allure report
      run: |
        allure generate reports/allure-results -o reports/allure-report --clean

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-report
