name: pytest + Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List all project files
        run: ls -R

      - name: Debug: List tests folder
        run: |
          echo "Listing all files in tests folder:"
          ls -R tests/

      - name: Run pytest with Allure results
        continue-on-error: true   # <-- must be here, at the step level
        run: |
          mkdir -p reports/allure-results
          pytest tests/ --maxfail=1 --disable-warnings -v --alluredir=reports/allure-results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline --no-update-notifier --no-fund --silent

      - name: Generate Allure HTML report
        if: always()
        run: allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
