name: ThinkPalm Assignment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest and generate Allure results
        run: pytest --alluredir=reports/allure-results -v

      - name: Generate Allure report
        run: allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports/allure-report/
